service: telegram-bot

# throw error before trying to deploy if something is wrong in config
configValidationMode: error

# create an optimized package for our functions
package:
  individually: true

custom:
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: false # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

plugins:
  - serverless-webpack # https://github.com/serverless-heaven/serverless-webpack

provider:
  
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  region: eu-central-1
  environment:
    # telegram
    TELEGRAM_BOT_API_KEY: ${ssm:/dg-telegram-bot-api-key}

    # twitter
    TWITTER_API_KEY: ${ssm:/twitter-api-key}
    TWITTER_API_KEY_SECRET: ${ssm:/twitter-api-key-secret}
    TWITTER_BEARER_TOKEN: ${ssm:/twitter-bearer-token}

    # finnhub
    FINNHUB_TOKEN: ${ssm:/finnhub-token}

    # binance
    BINANCE_API_KEY: ${ssm:/binance_api_key}
    BINANCE_SECRET_KEY: ${ssm:/binance_secret_key}
    BINANCE_URL: https://api.binance.com/api/v3

    # kraken
    KRAKEN_API_KEY: ${ssm:/kraken_api_key}
    KRAKEN_SECRET_KEY: ${ssm:/kraken_secret_key}
    KRAKEN_URL: 'https://api.kraken.com'

    # general
    CURRENCY: EUR

functions:

  bot:
    handler: src/lambda/bot.handler
    events:
      - http:
          method: post
          path: bot
          cors: true