name: pr-workflow

on:
  pull_request:
    branches:
      - develop

env:
  NODE_VERSION: 14
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      