name: pr-workflow

on:
  pull_request

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Setup node
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Setup node
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run build